code

equ trap_Printf_real									  -1	; G_PRINT 
equ trap_Error_real										  -2	; G_ERROR 
equ trap_Milliseconds_real								  -3	; G_MILLISECONDS 
equ trap_Cvar_Register_real								  -4	; G_CVAR_REGISTER 
equ trap_Cvar_Update_real								  -5	; G_CVAR_UPDATE 
equ trap_Cvar_Set_real									  -6	; G_CVAR_SET 
equ trap_Cvar_VariableIntegerValue_real					  -7	; G_CVAR_VARIABLE_INTEGER_VALUE 
equ trap_Cvar_VariableStringBuffer_real					  -8	; G_CVAR_VARIABLE_STRING_BUFFER 
equ trap_Argc_real										  -9	; G_ARGC 
equ trap_Argv_real										 -10	; G_ARGV 
equ trap_FS_FOpenFile_real								 -11	; G_FS_FOPEN_FILE 
equ trap_FS_Read_real									 -12	; G_FS_READ 
equ trap_FS_Write_real									 -13	; G_FS_WRITE 
equ trap_FS_FCloseFile_real								 -14	; G_FS_FCLOSE_FILE 
equ trap_SendConsoleCommand_real						 -15	; G_SEND_CONSOLE_COMMAND 
equ trap_LocateGameData_real							 -16	; G_LOCATE_GAME_DATA 
equ trap_DropClient_real								 -17	; G_DROP_CLIENT 
equ trap_SendServerCommand_real							 -18	; G_SEND_SERVER_COMMAND 
equ trap_SetConfigstring_real							 -19	; G_SET_CONFIGSTRING 
equ trap_GetConfigstring_real							 -20	; G_GET_CONFIGSTRING 
equ trap_GetUserinfo_real								 -21	; G_GET_USERINFO 
equ trap_SetUserinfo_real								 -22	; G_SET_USERINFO 
equ trap_GetServerinfo_real								 -23	; G_GET_SERVERINFO 
equ trap_SetBrushModel_real								 -24	; G_SET_BRUSH_MODEL 
equ trap_Trace_real										 -25	; G_TRACE 
equ trap_PointContents_real								 -26	; G_POINT_CONTENTS 
equ trap_InPVS_real										 -27	; G_IN_PVS 
equ trap_InPVSIgnorePortals_real						 -28	; G_IN_PVS_IGNORE_PORTALS 
equ trap_AdjustAreaPortalState_real						 -29	; G_ADJUST_AREA_PORTAL_STATE 
equ trap_AreasConnected_real							 -30	; G_AREAS_CONNECTED 
equ trap_LinkEntity_real								 -31	; G_LINKENTITY 
equ trap_UnlinkEntity_real								 -32	; G_UNLINKENTITY 
equ trap_EntitiesInBox_real								 -33	; G_ENTITIES_IN_BOX 
equ trap_EntityContact_real								 -34	; G_ENTITY_CONTACT 
equ trap_BotAllocateClient_real							 -35	; G_BOT_ALLOCATE_CLIENT 
equ trap_BotFreeClient_real								 -36	; G_BOT_FREE_CLIENT 
equ trap_GetUsercmd_real								 -37	; G_GET_USERCMD 
equ trap_GetEntityToken_real							 -38	; G_GET_ENTITY_TOKEN 
equ trap_FS_GetFileList_real							 -39	; G_FS_GETFILELIST 
equ trap_DebugPolygonCreate_real						 -40	; G_DEBUG_POLYGON_CREATE 
equ trap_DebugPolygonDelete_real						 -41	; G_DEBUG_POLYGON_DELETE 
equ trap_RealTime_real									 -42	; G_REAL_TIME 
equ trap_SnapVector_real								 -43	; G_SNAPVECTOR 
equ trap_TraceCapsule_real								 -44	; G_TRACECAPSULE 
equ trap_EntityContactCapsule_real						 -45	; G_ENTITY_CONTACTCAPSULE 
equ trap_SP_RegisterServer_real							 -46	; SP_REGISTER_SERVER_CMD 
equ trap_SP_GetStringTextString_real					 -47	; SP_GETSTRINGTEXTSTRING 
equ trap_ROFF_Clean_real								 -48	; G_ROFF_CLEAN 
equ trap_ROFF_UpdateEntities_real						 -49	; G_ROFF_UPDATE_ENTITIES 
equ trap_ROFF_Cache_real								 -50	; G_ROFF_CACHE 
equ trap_ROFF_Play_real									 -51	; G_ROFF_PLAY 
equ trap_ROFF_Purge_Ent_real							 -52	; G_ROFF_PURGE_ENT 
equ trap_BotLibSetup_real								-201	; BOTLIB_SETUP 
equ trap_BotLibShutdown_real							-202	; BOTLIB_SHUTDOWN 
equ trap_BotLibVarSet_real								-203	; BOTLIB_LIBVAR_SET 
equ trap_BotLibVarGet_real								-204	; BOTLIB_LIBVAR_GET 
equ trap_BotLibDefine_real								-205	; BOTLIB_PC_ADD_GLOBAL_DEFINE 
equ trap_BotLibStartFrame_real							-206	; BOTLIB_START_FRAME 
equ trap_BotLibLoadMap_real								-207	; BOTLIB_LOAD_MAP 
equ trap_BotLibUpdateEntity_real						-208	; BOTLIB_UPDATENTITY 
equ trap_BotLibTest_real								-209	; BOTLIB_TEST 
equ trap_BotGetSnapshotEntity_real						-210	; BOTLIB_GET_SNAPSHOT_ENTITY 
equ trap_BotGetServerCommand_real						-211	; BOTLIB_GET_CONSOLE_MESSAGE 
equ trap_BotUserCommand_real							-212	; BOTLIB_USER_COMMAND 
equ trap_AAS_EntityInfo_real							-304	; BOTLIB_AAS_ENTITY_INFO 
equ trap_AAS_Initialized_real							-305	; BOTLIB_AAS_INITIALIZED 
equ trap_AAS_PresenceTypeBoundingBox_real				-306	; BOTLIB_AAS_PRESENCE_TYPE_BOUNDING_BOX 
equ trap_AAS_Time_real									-307	; BOTLIB_AAS_TIME 
equ trap_AAS_PointAreaNum_real							-308	; BOTLIB_AAS_POINT_AREA_NUM 
equ trap_AAS_PointReachabilityAreaIndex_real			-578	; BOTLIB_AAS_POINT_REACHABILITY_AREA_INDEX 
equ trap_AAS_TraceAreas_real							-309	; BOTLIB_AAS_TRACE_AREAS 
equ trap_AAS_BBoxAreas_real								-302	; BOTLIB_AAS_BBOX_AREAS 
equ trap_AAS_AreaInfo_real								-303	; BOTLIB_AAS_AREA_INFO 
equ trap_AAS_PointContents_real							-310	; BOTLIB_AAS_POINT_CONTENTS 
equ trap_AAS_NextBSPEntity_real							-311	; BOTLIB_AAS_NEXT_BSP_ENTITY 
equ trap_AAS_ValueForBSPEpairKey_real					-312	; BOTLIB_AAS_VALUE_FOR_BSP_EPAIR_KEY 
equ trap_AAS_VectorForBSPEpairKey_real					-313	; BOTLIB_AAS_VECTOR_FOR_BSP_EPAIR_KEY 
equ trap_AAS_FloatForBSPEpairKey_real					-314	; BOTLIB_AAS_FLOAT_FOR_BSP_EPAIR_KEY 
equ trap_AAS_IntForBSPEpairKey_real						-315	; BOTLIB_AAS_INT_FOR_BSP_EPAIR_KEY 
equ trap_AAS_AreaReachability_real						-316	; BOTLIB_AAS_AREA_REACHABILITY 
equ trap_AAS_AreaTravelTimeToGoalArea_real				-317	; BOTLIB_AAS_AREA_TRAVEL_TIME_TO_GOAL_AREA 
equ trap_AAS_EnableRoutingArea_real						-301	; BOTLIB_AAS_ENABLE_ROUTING_AREA 
equ trap_AAS_PredictRoute_real							-577	; BOTLIB_AAS_PREDICT_ROUTE 
equ trap_AAS_AlternativeRouteGoals_real					-576	; BOTLIB_AAS_ALTERNATIVE_ROUTE_GOAL 
equ trap_AAS_Swimming_real								-318	; BOTLIB_AAS_SWIMMING 
equ trap_AAS_PredictClientMovement_real					-319	; BOTLIB_AAS_PREDICT_CLIENT_MOVEMENT 
equ trap_EA_Say_real									-401	; BOTLIB_EA_SAY 
equ trap_EA_SayTeam_real								-402	; BOTLIB_EA_SAY_TEAM 
equ trap_EA_Command_real								-403	; BOTLIB_EA_COMMAND 
equ trap_EA_Action_real									-404	; BOTLIB_EA_ACTION 
equ trap_EA_Gesture_real								-405	; BOTLIB_EA_GESTURE 
equ trap_EA_Talk_real									-406	; BOTLIB_EA_TALK 
equ trap_EA_Attack_real									-407	; BOTLIB_EA_ATTACK 
equ trap_EA_Alt_Attack_real								-408	; BOTLIB_EA_ALT_ATTACK 
equ trap_EA_ForcePower_real								-409	; BOTLIB_EA_FORCEPOWER 
equ trap_EA_Use_real									-410	; BOTLIB_EA_USE 
equ trap_EA_Respawn_real								-411	; BOTLIB_EA_RESPAWN 
equ trap_EA_Crouch_real									-412	; BOTLIB_EA_CROUCH 
equ trap_EA_MoveUp_real									-413	; BOTLIB_EA_MOVE_UP 
equ trap_EA_MoveDown_real								-414	; BOTLIB_EA_MOVE_DOWN 
equ trap_EA_MoveForward_real							-415	; BOTLIB_EA_MOVE_FORWARD 
equ trap_EA_MoveBack_real								-416	; BOTLIB_EA_MOVE_BACK 
equ trap_EA_MoveLeft_real								-417	; BOTLIB_EA_MOVE_LEFT 
equ trap_EA_MoveRight_real								-418	; BOTLIB_EA_MOVE_RIGHT 
equ trap_EA_SelectWeapon_real							-419	; BOTLIB_EA_SELECT_WEAPON 
equ trap_EA_Jump_real									-420	; BOTLIB_EA_JUMP 
equ trap_EA_DelayedJump_real							-421	; BOTLIB_EA_DELAYED_JUMP 
equ trap_EA_Move_real									-422	; BOTLIB_EA_MOVE 
equ trap_EA_View_real									-423	; BOTLIB_EA_VIEW 
equ trap_EA_EndRegular_real								-424	; BOTLIB_EA_END_REGULAR 
equ trap_EA_GetInput_real								-425	; BOTLIB_EA_GET_INPUT 
equ trap_EA_ResetInput_real								-426	; BOTLIB_EA_RESET_INPUT 
equ trap_BotLoadCharacter_real							-501	; BOTLIB_AI_LOAD_CHARACTER 
equ trap_BotFreeCharacter_real							-502	; BOTLIB_AI_FREE_CHARACTER 
equ trap_Characteristic_Float_real						-503	; BOTLIB_AI_CHARACTERISTIC_FLOAT 
equ trap_Characteristic_BFloat_real						-504	; BOTLIB_AI_CHARACTERISTIC_BFLOAT 
equ trap_Characteristic_Integer_real					-505	; BOTLIB_AI_CHARACTERISTIC_INTEGER 
equ trap_Characteristic_BInteger_real					-506	; BOTLIB_AI_CHARACTERISTIC_BINTEGER 
equ trap_Characteristic_String_real						-507	; BOTLIB_AI_CHARACTERISTIC_STRING 
equ trap_BotAllocChatState_real							-508	; BOTLIB_AI_ALLOC_CHAT_STATE 
equ trap_BotFreeChatState_real							-509	; BOTLIB_AI_FREE_CHAT_STATE 
equ trap_BotQueueConsoleMessage_real					-510	; BOTLIB_AI_QUEUE_CONSOLE_MESSAGE 
equ trap_BotRemoveConsoleMessage_real					-511	; BOTLIB_AI_REMOVE_CONSOLE_MESSAGE 
equ trap_BotNextConsoleMessage_real						-512	; BOTLIB_AI_NEXT_CONSOLE_MESSAGE 
equ trap_BotNumConsoleMessages_real						-513	; BOTLIB_AI_NUM_CONSOLE_MESSAGE 
equ trap_BotInitialChat_real							-514	; BOTLIB_AI_INITIAL_CHAT 
equ trap_BotNumInitialChats_real						-570	; BOTLIB_AI_NUM_INITIAL_CHATS 
equ trap_BotReplyChat_real								-515	; BOTLIB_AI_REPLY_CHAT 
equ trap_BotChatLength_real								-516	; BOTLIB_AI_CHAT_LENGTH 
equ trap_BotEnterChat_real								-517	; BOTLIB_AI_ENTER_CHAT 
equ trap_BotGetChatMessage_real							-571	; BOTLIB_AI_GET_CHAT_MESSAGE 
equ trap_StringContains_real							-518	; BOTLIB_AI_STRING_CONTAINS 
equ trap_BotFindMatch_real								-519	; BOTLIB_AI_FIND_MATCH 
equ trap_BotMatchVariable_real							-520	; BOTLIB_AI_MATCH_VARIABLE 
equ trap_UnifyWhiteSpaces_real							-521	; BOTLIB_AI_UNIFY_WHITE_SPACES 
equ trap_BotReplaceSynonyms_real						-522	; BOTLIB_AI_REPLACE_SYNONYMS 
equ trap_BotLoadChatFile_real							-523	; BOTLIB_AI_LOAD_CHAT_FILE 
equ trap_BotSetChatGender_real							-524	; BOTLIB_AI_SET_CHAT_GENDER 
equ trap_BotSetChatName_real							-525	; BOTLIB_AI_SET_CHAT_NAME 
equ trap_BotResetGoalState_real							-526	; BOTLIB_AI_RESET_GOAL_STATE 
equ trap_BotResetAvoidGoals_real						-527	; BOTLIB_AI_RESET_AVOID_GOALS 
equ trap_BotRemoveFromAvoidGoals_real					-572	; BOTLIB_AI_REMOVE_FROM_AVOID_GOALS 
equ trap_BotPushGoal_real								-528	; BOTLIB_AI_PUSH_GOAL 
equ trap_BotPopGoal_real								-529	; BOTLIB_AI_POP_GOAL 
equ trap_BotEmptyGoalStack_real							-530	; BOTLIB_AI_EMPTY_GOAL_STACK 
equ trap_BotDumpAvoidGoals_real							-531	; BOTLIB_AI_DUMP_AVOID_GOALS 
equ trap_BotDumpGoalStack_real							-532	; BOTLIB_AI_DUMP_GOAL_STACK 
equ trap_BotGoalName_real								-533	; BOTLIB_AI_GOAL_NAME 
equ trap_BotGetTopGoal_real								-534	; BOTLIB_AI_GET_TOP_GOAL 
equ trap_BotGetSecondGoal_real							-535	; BOTLIB_AI_GET_SECOND_GOAL 
equ trap_BotChooseLTGItem_real							-536	; BOTLIB_AI_CHOOSE_LTG_ITEM 
equ trap_BotChooseNBGItem_real							-537	; BOTLIB_AI_CHOOSE_NBG_ITEM 
equ trap_BotTouchingGoal_real							-538	; BOTLIB_AI_TOUCHING_GOAL 
equ trap_BotItemGoalInVisButNotVisible_real				-539	; BOTLIB_AI_ITEM_GOAL_IN_VIS_BUT_NOT_VISIBLE 
equ trap_BotGetLevelItemGoal_real						-540	; BOTLIB_AI_GET_LEVEL_ITEM_GOAL 
equ trap_BotGetNextCampSpotGoal_real					-568	; BOTLIB_AI_GET_NEXT_CAMP_SPOT_GOAL 
equ trap_BotGetMapLocationGoal_real						-569	; BOTLIB_AI_GET_MAP_LOCATION_GOAL 
equ trap_BotAvoidGoalTime_real							-541	; BOTLIB_AI_AVOID_GOAL_TIME 
equ trap_BotSetAvoidGoalTime_real						-574	; BOTLIB_AI_SET_AVOID_GOAL_TIME 
equ trap_BotInitLevelItems_real							-542	; BOTLIB_AI_INIT_LEVEL_ITEMS 
equ trap_BotUpdateEntityItems_real						-543	; BOTLIB_AI_UPDATE_ENTITY_ITEMS 
equ trap_BotLoadItemWeights_real						-544	; BOTLIB_AI_LOAD_ITEM_WEIGHTS 
equ trap_BotFreeItemWeights_real						-545	; BOTLIB_AI_FREE_ITEM_WEIGHTS 
equ trap_BotInterbreedGoalFuzzyLogic_real				-566	; BOTLIB_AI_INTERBREED_GOAL_FUZZY_LOGIC 
equ trap_BotSaveGoalFuzzyLogic_real						-546	; BOTLIB_AI_SAVE_GOAL_FUZZY_LOGIC 
equ trap_BotMutateGoalFuzzyLogic_real					-567	; BOTLIB_AI_MUTATE_GOAL_FUZZY_LOGIC 
equ trap_BotAllocGoalState_real							-547	; BOTLIB_AI_ALLOC_GOAL_STATE 
equ trap_BotFreeGoalState_real							-548	; BOTLIB_AI_FREE_GOAL_STATE 
equ trap_BotResetMoveState_real							-549	; BOTLIB_AI_RESET_MOVE_STATE 
equ trap_BotAddAvoidSpot_real							-575	; BOTLIB_AI_ADD_AVOID_SPOT 
equ trap_BotMoveToGoal_real								-550	; BOTLIB_AI_MOVE_TO_GOAL 
equ trap_BotMoveInDirection_real						-551	; BOTLIB_AI_MOVE_IN_DIRECTION 
equ trap_BotResetAvoidReach_real						-552	; BOTLIB_AI_RESET_AVOID_REACH 
equ trap_BotResetLastAvoidReach_real					-553	; BOTLIB_AI_RESET_LAST_AVOID_REACH 
equ trap_BotReachabilityArea_real						-554	; BOTLIB_AI_REACHABILITY_AREA 
equ trap_BotMovementViewTarget_real						-555	; BOTLIB_AI_MOVEMENT_VIEW_TARGET 
equ trap_BotPredictVisiblePosition_real					-573	; BOTLIB_AI_PREDICT_VISIBLE_POSITION 
equ trap_BotAllocMoveState_real							-556	; BOTLIB_AI_ALLOC_MOVE_STATE 
equ trap_BotFreeMoveState_real							-557	; BOTLIB_AI_FREE_MOVE_STATE 
equ trap_BotInitMoveState_real							-558	; BOTLIB_AI_INIT_MOVE_STATE 
equ trap_BotChooseBestFightWeapon_real					-559	; BOTLIB_AI_CHOOSE_BEST_FIGHT_WEAPON 
equ trap_BotGetWeaponInfo_real							-560	; BOTLIB_AI_GET_WEAPON_INFO 
equ trap_BotLoadWeaponWeights_real						-561	; BOTLIB_AI_LOAD_WEAPON_WEIGHTS 
equ trap_BotAllocWeaponState_real						-562	; BOTLIB_AI_ALLOC_WEAPON_STATE 
equ trap_BotFreeWeaponState_real						-563	; BOTLIB_AI_FREE_WEAPON_STATE 
equ trap_BotResetWeaponState_real						-564	; BOTLIB_AI_RESET_WEAPON_STATE 
equ trap_GeneticParentsAndChildSelection_real			-565	; BOTLIB_AI_GENETIC_PARENTS_AND_CHILD_SELECTION 
equ trap_PC_LoadSource_real								-579	; BOTLIB_PC_LOAD_SOURCE 
equ trap_PC_FreeSource_real								-580	; BOTLIB_PC_FREE_SOURCE 
equ trap_PC_ReadToken_real								-581	; BOTLIB_PC_READ_TOKEN 
equ trap_PC_SourceFileAndLine_real						-582	; BOTLIB_PC_SOURCE_FILE_AND_LINE 
equ trap_G2_ListModelBones_real							-583	; G_G2_LISTBONES 
equ trap_G2_ListModelSurfaces_real						-584	; G_G2_LISTSURFACES 
equ trap_G2_HaveWeGhoul2Models_real						-585	; G_G2_HAVEWEGHOULMODELS 
equ trap_G2_SetGhoul2ModelIndexes_real					-586	; G_G2_SETMODELS 
equ trap_G2API_GetBoltMatrix_real						-587	; G_G2_GETBOLT 
equ trap_G2API_GetBoltMatrix_NoReconstruct_real			-588	; G_G2_GETBOLT_NOREC 

equ trap_G2API_InitGhoul2Model_1_02_real				-589	; G_G2_INITGHOUL2MODEL 
equ trap_G2API_AddBolt_1_02_real						-590	; G_G2_ADDBOLT 
equ trap_G2API_SetBoltInfo_1_02_real					-591	; G_G2_SETBOLTINFO 
equ trap_G2API_SetBoneAngles_1_02_real					-592	; G_G2_ANGLEOVERRIDE 
equ trap_G2API_SetBoneAnim_1_02_real					-593	; G_G2_PLAYANIM 
equ trap_G2API_GetGLAName_1_02_real						-594	; G_G2_GETGLANAME 
equ trap_G2API_CopyGhoul2Instance_1_02_real				-595	; G_G2_COPYGHOUL2INSTANCE 
equ trap_G2API_CopySpecificGhoul2Model_1_02_real		-596	; G_G2_COPYSPECIFICGHOUL2MODEL 
equ trap_G2API_DuplicateGhoul2Instance_1_02_real		-597	; G_G2_DUPLICATEGHOUL2INSTANCE 
equ trap_G2API_HasGhoul2ModelOnIndex_1_02_real			-598	; G_G2_HASGHOUL2MODELONINDEX 
equ trap_G2API_RemoveGhoul2Model_1_02_real				-599	; G_G2_REMOVEGHOUL2MODEL 
equ trap_G2API_CleanGhoul2Models_1_02_real				-600	; G_G2_CLEANMODELS 

equ trap_G2API_GetBoltMatrix_NoRecNoRot_1_04_real		-589	; G_G2_GETBOLT_NOREC_NOROT 
equ trap_G2API_InitGhoul2Model_1_04_real				-590	; G_G2_INITGHOUL2MODEL 
equ trap_G2API_AddBolt_1_04_real						-591	; G_G2_ADDBOLT 
equ trap_G2API_SetBoltInfo_1_04_real					-592	; G_G2_SETBOLTINFO 
equ trap_G2API_SetBoneAngles_1_04_real					-593	; G_G2_ANGLEOVERRIDE 
equ trap_G2API_SetBoneAnim_1_04_real					-594	; G_G2_PLAYANIM 
equ trap_G2API_GetGLAName_1_04_real						-595	; G_G2_GETGLANAME 
equ trap_G2API_CopyGhoul2Instance_1_04_real				-596	; G_G2_COPYGHOUL2INSTANCE 
equ trap_G2API_CopySpecificGhoul2Model_1_04_real		-597	; G_G2_COPYSPECIFICGHOUL2MODEL 
equ trap_G2API_DuplicateGhoul2Instance_1_04_real		-598	; G_G2_DUPLICATEGHOUL2INSTANCE 
equ trap_G2API_HasGhoul2ModelOnIndex_1_04_real			-599	; G_G2_HASGHOUL2MODELONINDEX 
equ trap_G2API_RemoveGhoul2Model_1_04_real				-600	; G_G2_REMOVEGHOUL2MODEL 
equ trap_G2API_CleanGhoul2Models_1_04_real				-601	; G_G2_CLEANMODELS 
equ trap_G2API_CollisionDetect_1_04_real				-602	; G_G2_COLLISIONDETECT 


; hardcoded functions
equ memset												-101	; G_MEMSET 
equ memcpy												-102	; G_MEMCPY 
equ strncpy												-103	; G_STRNCPY 
equ sin													-104	; G_SIN 
equ cos													-105	; G_COS 
equ atan2												-106	; G_ATAN2 
equ sqrt												-107	; G_SQRT 
equ matrixmultiply										-108	; G_MATRIXMULTIPLY 
equ anglevectors										-109	; G_ANGLEVECTORS 
equ perpendicularvector									-110	; G_PERPENDICULARVECTOR 
equ floor												-111	; G_FLOOR 
equ ceil												-112	; G_CEIL 
equ acos												-115	; G_ACOS 
equ asin												-116	; G_ASIN 

; JK2MV Syscalls [Universal]
equ trap_MVAPI_ControlFixes								-704	;MVAPI_CONTROL_FIXES
equ trap_MVAPI_GetVersion								-705    ;MVAPI_GET_VERSION
equ trap_FS_FLock										-709	;MVAPI_FS_FLOCK
equ trap_MVAPI_SetVersion								-710	;MVAPI_SET_VERSION

; JK2MV Syscalls [Game]
equ trap_MVAPI_SendConnectionlessPacket					-701	;G_MVAPI_SEND_CONNECTIONLESSPACKET
equ trap_MVAPI_GetConnectionlessPacket					-702	;G_MVAPI_GET_CONNECTIONLESSPACKET
equ trap_MVAPI_LocateGameData							-703	;G_MVAPI_LOCATE_GAME_DATA
equ trap_MVAPI_DisableStructConversion					-706	;G_MVAPI_DISABLE_STRUCT_CONVERSION
